### ISSUE TITLE
USB-CDC class for serial communication via USB

### ISSUE THREAD

**Issue by adamvm** [DISTORTEC/distortosExamples#3]
What is the best approach to integrate USB-CDC sources available with CubeMX with Distortos?

**Comment by FreddieChopin** [comment]
Hello Adam!

What board do you have at your disposal? If I have the same one (or something very similar) I could prepare an example project, similar to this one - https://github.com/DISTORTEC/STM32F7-USB-host-ME906-lwIP-MQTT . Generally the idea is very similar as shown in that project, but I know how helpful is to have something that is known to work, so I could make such package and publish it on GitHub.

**Comment by adamvm** [comment]
My main platform i Nucleo F767zi. It would be verry helpful to have package from you.
My focus is on CMake and C++ for STMs. Currently I study Multithreading with this course class https://github.com/coders-school/multithreading
