### ISSUE TITLE
I2C example

### ISSUE THREAD

**Issue by adamvm** [DISTORTEC/distortosExamples#4]
Can we have example of I2C usage?
If there is need to development I can support

**Comment by adamvm** [comment]
I would like to use DAC MCP4725 and display with SSD1306 in first place.
I expect that on the side of DISTORTOS would be bus configuration, send and receive command while specific operation on the devices would be part of my external libraries

**Comment by FreddieChopin** [comment]
At this moment there is no support for I2C in distortos. Therefore I'm not able to provide you with any examples or hints, at least now... There is nothing stopping you from using your own code or trying to adapt the code from some external source (like the CubeMX libraries).
